spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/just_pay
    username: root
    password: 2465
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
